In [2]:
import numpy as np
np.__version__

'1.26.4'

In [33]:
import warnings
warnings.filterwarnings("ignore")

In [1]:
print("hello")

hello


Linear Algebra: Simple array Operations
transpose(),linalg.inv(),eye(),@,trace(),linalg.solve(),linalg.eig()

In [3]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [5]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
b=np.eye(2)  # # unit 2x2 matrix; "eye" represents "I"
print(b)

[[1. 0.]
 [0. 1.]]


In [8]:
c=np.array([[0,-1],[1,0]])
c@c  # matrix product

array([[-1,  0],
       [ 0, -1]])

In [9]:
np.trace(b)

2.0

In [10]:
y=np.array([[5],[7]])
np.linalg.solve(a,y)

array([[-3.],
       [ 4.]])

In [11]:
np.linalg.eig(c)

EigResult(eigenvalues=array([0.+1.j, 0.-1.j]), eigenvectors=array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]]))

Create Array:array,zeros,random.rand  and slicing

In [12]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [13]:
arr2=np.zeros((3,4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
arr3=np.random.rand(3,4)
arr3

array([[0.72731383, 0.2210876 , 0.66221867, 0.92256942],
       [0.22789368, 0.29055381, 0.1142689 , 0.5300216 ],
       [0.56152583, 0.79433449, 0.4068256 , 0.63822776]])

In [16]:
arr3[:2,:] #first two rows and all columns

array([[0.72731383, 0.2210876 , 0.66221867, 0.92256942],
       [0.22789368, 0.29055381, 0.1142689 , 0.5300216 ]])

In [17]:
arr3[0,::2] #every other element in the first row

array([0.72731383, 0.66221867])

In [18]:
arr3[:2,:]

array([[0.72731383, 0.2210876 , 0.66221867, 0.92256942],
       [0.22789368, 0.29055381, 0.1142689 , 0.5300216 ]])

In [19]:
arr3[:,-1]

array([0.92256942, 0.5300216 , 0.63822776])

In [20]:
arr = np.array([11,23,35,47,51,64,72]) #Slicing(start,stop,end)
print("1. ",arr[1:5])
print("2.  ",arr[1:])
print("3.  ",arr[:4])
print("4.  ",arr[-3:-1])
print("5.  ",arr[::2])
print("6.  ",arr[::-1])

1.  [23 35 47 51]
2.   [23 35 47 51 64 72]
3.   [11 23 35 47]
4.   [51 64]
5.   [11 35 51 72]
6.   [72 64 51 47 35 23 11]


In [21]:
arr = np.array([11,23,35,47,51,64,72]) #append
arr = np.append(arr, 15)
print(arr)

[11 23 35 47 51 64 72 15]


In [22]:
arr = np.array([11,23,35,47,51,64,72]) #Concatenate
arr1 = np.array([15,25,65,49,11,84,32])
newArr = np.concatenate((arr, arr1))
print(newArr)

[11 23 35 47 51 64 72 15 25 65 49 11 84 32]


In [23]:
arr = np.array([11,23,35,47,51,64,72]) #replace element
arr[1]=40
print(arr)

[11 40 35 47 51 64 72]


In [28]:
arr = np.array([1, 2, 3, 4])
deleted_arr = np.delete(arr, 1) # Delete second element
print(deleted_arr) # Output: [1 3 4]

[1 3 4]


In [29]:
arr = np.array([3, 1, 4, 2])  
sorted_arr = np.sort(arr) # Sort in ascending order
print(sorted_arr) # Output: [1 2 3 4]

[1 2 3 4]


In [30]:
arr = np.array([3, 1, 4, 2])
sorted_indices = np.argsort(arr)
print(sorted_indices) # Output: [1 0 3 2]

[1 3 0 2]


In [35]:
# NaN example
x = np.array([1.0, 0.0, -1.0])
y = np.log(x) # Attempting to take the logarithm of 0 result
 #s in NaN
print(y) # Output: [ 0. -inf nan]
# INF example
z = np.array([2.0, 4.0, 6.0])
w = np.divide(z, 0) # Division by zero results in INF
w # Output: [inf inf inf]

[  0. -inf  nan]


array([inf, inf, inf])

In [36]:
min_value = np.min(arr)
max_value = np.max(arr)
print(min_value) # Output: 1
print(max_value) # Output: 5

1
4


In [37]:
std_deviation = np.std(arr)
variance = np.var(arr)
print(std_deviation) # Output: 1.4142135623730951
print(variance) # Output: 2.0

1.118033988749895
1.25


In [38]:
lin=np.linspace(1,1000,10)
print(lin)

[   1.  112.  223.  334.  445.  556.  667.  778.  889. 1000.]


In [39]:
y=np.random.randn(4,3)
y

array([[-0.31278702, -0.34427545, -1.01328162],
       [ 0.6156671 , -0.20245626, -2.63675061],
       [ 0.78971802, -1.09629924, -0.87589376],
       [ 2.06600147, -0.23500609,  0.57424657]])

In [40]:
arry=np.array([2,4,6,8])
rep=np.repeat(arry,3)
rep

array([2, 2, 2, 4, 4, 4, 6, 6, 6, 8, 8, 8])

In [41]:
tile=np.tile(arry,3)
tile #coam added

array([2, 4, 6, 8, 2, 4, 6, 8, 2, 4, 6, 8])

In [46]:
### File Read and Write
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
file_path = "data.txt" # file location select c/d/e/f/ drive
with open(file_path, 'w') as file:
    for row in data:
        row_str = ' '.join(map(str, row))
        file.write(row_str + '\n')
read_data = []
with open(file_path, 'r') as file:
    for line in file:
        row_data = list(map(int, line.strip().split()))
        read_data.append(row_data)
read_data = np.array(read_data)
print("Data read from file:")
print(read_data)
print(file_path)

Data read from file:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
data.txt


In [47]:
# min,max,argmax,argmin

arrr3=np.random.randint(0,100,10)
print("1.",   arrr3.max())
print("2.",   arrr3.min())
print("3.",   arrr3.argmax())
print("4.",   arrr3.argmin())  # position start 0

1. 93
2. 0
3. 5
4. 9


In [48]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [49]:
np.ones((4,2),dtype="float")

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
np.random.randint(-4,8,size=(3,3))

array([[ 6,  4,  2],
       [ 0, -1, -4],
       [ 0,  7,  2]])

In [51]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
Flat_arr = arr.flatten()
print(Flat_arr)


[1 2 3 4 5 6]
